---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 12.4.3

provisioner:
  name: chef_solo

platforms:
 - name: centos-6.5
   driver_config:
      box: centos65
      box_url: https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box


suites:
  - name: default
    run_list:
      - recipe[nginx_example::default]
    attributes:
